CREATE TABLE IF NOT EXISTS leaderboard (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    player_number INTEGER NOT NULL UNIQUE,
    winrate REAL DEFAULT 0.0,
    goal INTEGER DEFAULT 0,
    assist INTEGER DEFAULT 0,
    total_match INTEGER DEFAULT 0,
    total_win INTEGER DEFAULT 0,
    total_lose INTEGER DEFAULT 0,
    total_draw INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS player (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tele_id INTEGER NOT NULL UNIQUE,
    number INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL,
    username TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);